TRUNCATE TABLE connector CASCADE;
TRUNCATE TABLE device CASCADE;
TRUNCATE TABLE station CASCADE;

ALTER SEQUENCE station_id_seq RESTART WITH 1;
ALTER SEQUENCE device_id_seq RESTART WITH 1;
ALTER SEQUENCE connector_id_seq RESTART WITH 1;
